name: writefont
description: 手迹造字 - 拍照生成手写字体 WriteFont iOS Client
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.4
  image: ^4.1.3
  share_plus: ^7.2.1
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  google_fonts: ^6.1.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
