import 'dart:convert';
import 'dart:typed_data';
import 'dart:ui' show ImageByteFormat, PictureRecorder, Canvas, Color, Rect;
import 'package:archive/archive.dart';
import 'package:flutter/painting.dart';
import '../models/project.dart';
import 'ttf_builder.dart';
import 'woff_builder.dart';

/// 字体打包导出器
///
/// 将字体项目打包为包含多种格式的 ZIP：
/// - TTF 字体文件
/// - WOFF 字体文件
/// - CSS @font-face 代码片段
/// - 字体样本图片（不同字号的字符渲染）
class FontPackageExporter {
  FontPackageExporter._();

  /// 导出字体项目为打包 ZIP 字节
  ///
  /// 返回 ZIP 文件的二进制数据。
  static Future<Uint8List> exportPackage(FontProject project) async {
    final metadata = project.metadata;
    final familyName = metadata?.familyName ?? project.name;
    final safeName = familyName.replaceAll(RegExp(r'[^\w\-]'), '_');

    // 1. 构建 TTF
    final glyphs = project.glyphs.values.toList();
    final builder = TtfBuilder(
      glyphs: glyphs,
      familyName: project.name,
      unitsPerEm: 1000,
      kerningPairs: project.kerningPairs,
      customFamilyName: familyName,
      customSubfamilyName: metadata?.subfamilyName ?? 'Regular',
      customVersion: metadata?.version ?? 'Version 1.0',
      customCopyright: metadata?.copyright ?? '',
      customDescription: metadata?.description ?? '',
    );
    final ttfBytes = builder.build();

    // 2. 构建 WOFF
    final woffBuilder = WoffBuilder(ttfBytes: ttfBytes);
    final woffBytes = woffBuilder.build();

    // 3. 生成 CSS @font-face
    final cssContent = _generateCss(familyName, safeName);
    final cssBytes = utf8.encode(cssContent);

    // 4. 生成字体样本图片
    final samplePngBytes = await _generateSampleImage(
      ttfBytes: ttfBytes,
      familyName: familyName,
      sampleChars: _pickSampleChars(glyphs),
    );

    // 5. 生成 HTML 预览页
    final htmlContent = _generateHtmlPreview(familyName, safeName);
    final htmlBytes = utf8.encode(htmlContent);

    // 6. 打包 ZIP
    final archive = Archive();

    archive.addFile(ArchiveFile('$safeName.ttf', ttfBytes.length, ttfBytes));
    archive.addFile(ArchiveFile('$safeName.woff', woffBytes.length, woffBytes));
    archive.addFile(ArchiveFile('$safeName.css', cssBytes.length, cssBytes));
    archive.addFile(ArchiveFile('preview.html', htmlBytes.length, htmlBytes));
    if (samplePngBytes != null) {
      archive.addFile(ArchiveFile(
        '${safeName}_sample.png',
        samplePngBytes.length,
        samplePngBytes,
      ));
    }

    // README
    final readmeBytes = utf8.encode(_generateReadme(familyName));
    archive.addFile(ArchiveFile('README.txt', readmeBytes.length, readmeBytes));

    return Uint8List.fromList(ZipEncoder().encode(archive)!);
  }

  /// 生成 CSS @font-face 代码
  static String _generateCss(String familyName, String safeName) {
    return '''/* WriteFont 字体导出 — $familyName */
/* Generated by WriteFont v2.3.0 */

@font-face {
  font-family: '$familyName';
  src: url('$safeName.ttf') format('truetype'),
       url('$safeName.woff') format('woff');
  font-weight: normal;
  font-style: normal;
  font-display: swap;
}

/* 使用示例 */
/*
body {
  font-family: '$familyName', sans-serif;
}
*/
''';
  }

  /// 生成 HTML 预览页
  static String _generateHtmlPreview(String familyName, String safeName) {
    return '''<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>$familyName — 字体预览</title>
  <style>
    @font-face {
      font-family: '$familyName';
      src: url('$safeName.ttf') format('truetype'),
           url('$safeName.woff') format('woff');
      font-weight: normal;
      font-style: normal;
    }
    body {
      font-family: '$familyName', sans-serif;
      max-width: 800px;
      margin: 40px auto;
      padding: 0 20px;
      line-height: 1.8;
      color: #333;
    }
    h1 { font-size: 48px; border-bottom: 2px solid #eee; padding-bottom: 16px; }
    h2 { font-size: 24px; color: #666; margin-top: 32px; }
    .sample { margin: 16px 0; }
    .size-12 { font-size: 12px; }
    .size-16 { font-size: 16px; }
    .size-20 { font-size: 20px; }
    .size-24 { font-size: 24px; }
    .size-32 { font-size: 32px; }
    .size-48 { font-size: 48px; }
    .size-64 { font-size: 64px; }
    .dark { background: #1a1a2e; color: #fff; padding: 24px; border-radius: 8px; }
    code { background: #f4f4f4; padding: 2px 6px; border-radius: 4px; }
  </style>
</head>
<body>
  <h1>$familyName</h1>
  <p>由 WriteFont 手迹造字生成</p>

  <h2>字号阶梯</h2>
  <div class="sample size-12">12px — 天地玄黄，宇宙洪荒</div>
  <div class="sample size-16">16px — 天地玄黄，宇宙洪荒</div>
  <div class="sample size-20">20px — 天地玄黄，宇宙洪荒</div>
  <div class="sample size-24">24px — 天地玄黄，宇宙洪荒</div>
  <div class="sample size-32">32px — 天地玄黄，宇宙洪荒</div>
  <div class="sample size-48">48px — 天地玄黄</div>
  <div class="sample size-64">64px — 手迹</div>

  <h2>英文</h2>
  <div class="sample size-24">The quick brown fox jumps over the lazy dog</div>
  <div class="sample size-24">ABCDEFGHIJKLMNOPQRSTUVWXYZ</div>
  <div class="sample size-24">abcdefghijklmnopqrstuvwxyz</div>
  <div class="sample size-24">0123456789 !@#\$%^&*()</div>

  <h2>暗色背景</h2>
  <div class="dark">
    <div class="sample size-24">暗色背景下的字体效果</div>
    <div class="sample size-16">正文大小：天地玄黄，宇宙洪荒。日月盈昃，辰宿列张。</div>
  </div>

  <h2>CSS 使用方法</h2>
  <pre><code>@import url('$safeName.css');

body {
  font-family: '$familyName', sans-serif;
}</code></pre>
</body>
</html>
''';
  }

  /// 生成 README
  static String _generateReadme(String familyName) {
    return '''WriteFont 字体打包导出
======================

字体名称：$familyName
生成时间：${DateTime.now().toLocal()}
生成工具：WriteFont v2.3.0

文件说明：
- *.ttf        — TrueType 字体文件，适用于桌面系统安装
- *.woff       — Web Open Font Format，适用于网页嵌入
- *.css        — CSS @font-face 代码，可直接引入使用
- preview.html — 字体预览页面，用浏览器打开查看效果
- *_sample.png — 字体样本图片

使用方法：
1. 桌面安装：双击 .ttf 文件，点击"安装"
2. 网页使用：将 .ttf/.woff 和 .css 上传到服务器，在 HTML 中引入 CSS
3. 预览效果：用浏览器打开 preview.html

许可说明：
此字体由 WriteFont 手迹造字工具生成，请遵守相关许可协议。
''';
  }

  /// 选取样本字符（取前几个有轮廓的字符）
  static List<String> _pickSampleChars(List<GlyphData> glyphs) {
    final withContours = glyphs.where((g) => g.contours.isNotEmpty).toList();
    final chars = <String>[];
    for (final g in withContours.take(8)) {
      chars.add(g.character);
    }
    // 如果字符太少，补充默认字符
    if (chars.isEmpty) {
      chars.addAll(['字', '体', '预', '览']);
    }
    return chars;
  }

  /// 生成字体样本图片
  ///
  /// 使用 Canvas 绘制不同字号的字符，返回 PNG 字节。
  /// 由于 dart:ui 的 FontLoader 在 isolate 中不可用，
  /// 此方法生成一个简单的文字样本图片。
  static Future<Uint8List?> _generateSampleImage({
    required Uint8List ttfBytes,
    required String familyName,
    required List<String> sampleChars,
  }) async {
    try {
      const width = 800;
      const height = 400;
      final recorder = PictureRecorder();
      final canvas = Canvas(recorder);

      // 背景
      final bgPaint = Paint()..color = const Color(0xFFF8F9FA);
      canvas.drawRect(
        Rect.fromLTWH(0, 0, width.toDouble(), height.toDouble()),
        bgPaint,
      );

      // 标题
      final titlePainter = TextPainter(
        text: TextSpan(
          text: familyName,
          style: const TextStyle(
            fontSize: 32,
            fontWeight: FontWeight.bold,
            color: Color(0xFF333333),
          ),
        ),
        textDirection: TextDirection.ltr,
      );
      titlePainter.layout();
      titlePainter.paint(canvas, const Offset(40, 30));

      // 副标题
      final subtitlePainter = TextPainter(
        text: const TextSpan(
          text: 'WriteFont 字体样本',
          style: TextStyle(
            fontSize: 14,
            color: Color(0xFF999999),
          ),
        ),
        textDirection: TextDirection.ltr,
      );
      subtitlePainter.layout();
      subtitlePainter.paint(canvas, const Offset(40, 72));

      // 分隔线
      final linePaint = Paint()
        ..color = const Color(0xFFE0E0E0)
        ..strokeWidth = 1;
      canvas.drawLine(
        const Offset(40, 95),
        const Offset(760, 95),
        linePaint,
      );

      // 样本字符（不同字号）
      final sizes = [48.0, 36.0, 24.0, 18.0];
      double y = 110;
      final sampleText = sampleChars.join('  ');

      for (final size in sizes) {
        if (y > height - 50) break;
        final painter = TextPainter(
          text: TextSpan(
            text: sampleText,
            style: TextStyle(
              fontSize: size,
              color: const Color(0xFF333333),
            ),
          ),
          textDirection: TextDirection.ltr,
          maxLines: 1,
        );
        painter.layout(maxWidth: 720);
        painter.paint(canvas, Offset(40, y));
        y += size + 16;
      }

      // 底部信息
      final infoPainter = TextPainter(
        text: TextSpan(
          text: 'Generated by WriteFont · ${DateTime.now().year}',
          style: const TextStyle(
            fontSize: 11,
            color: Color(0xFFBBBBBB),
          ),
        ),
        textDirection: TextDirection.ltr,
      );
      infoPainter.layout();
      infoPainter.paint(
        canvas,
        Offset(40, height - 30.0),
      );

      final picture = recorder.endRecording();
      final image = await picture.toImage(width, height);
      final byteData = await image.toByteData(format: ImageByteFormat.png);
      image.dispose();

      if (byteData != null) {
        return byteData.buffer.asUint8List();
      }
      return null;
    } catch (e) {
      // 样本图片生成失败不影响打包
      return null;
    }
  }
}
